### PR TITLE
Fixes support for material-ui@5

### LINKED ISSUE #72: Does not work with @material-ui/core@5.0.0-alpha.5 or higher
Using `@material-ui/core@5.0.0-alpha.5` and higher, `material-ui-phone-number` produces the following error:

```
error - ./node_modules/material-ui-phone-number/dist/index.js:1:52871
Module not found: Can't resolve '@material-ui/core/RootRef'
```

### PR DESCRIPTION
**Pull request by varevarao**
Fixes #72 by extending #88

### CODE REVIEW

**Comment by bherila** [comment]
Working for me too. Thanks @varevarao !

**Comment by Jerome1337** [comment]
@Neodern how did you do? I cannot achieve to make it works

**Comment by bherila** [comment]
@Jerome1337  what is the problem you're having and what did you try?
Please note, SSR may not work yet. That's still in progress.

**Comment by Jerome1337** [comment]
@bherila I tried to require the master branch with npm/yarn without success so I cannot test if it's working on my project.

> Please note, SSR may not work yet. That's still in progress.
Oh ok, thanks for the info!

**Comment by bherila** [comment]
Most likely, I won't have time to continue working on this until the weekend. If you need something sooner, please implement it and send a PR 🙏

**Comment by Jerome1337** [comment]
@bherila We just need a new release from master to support material-ui v5.

Without this release we cannot use this lib with Mui@5

**Comment by bherila** [comment]
We need @alexplumb  to make the release, I don't have permissions on the npm module

@alexplumb  can you add me to the npm so I can at least release pre-release packages off master?

Also, I can help set up CI/CD off master branch here.

**Comment by alexplumb** [comment]
What's your npm username? I'll add you as a maintainer on that

**Comment by bherila** [comment]
@alexplumb  it's **bherila**, same as github

**Pull request merged**
