### PR TITLE
added nicer and easier to manage flags

### PR DESCRIPTION
**Pull request by masbaehr**
for #29
Tell me how you like it ;-)
I think it could be improved in size if JPG are used compared to PNG, but the quality could suffer

### CODE REVIEW

**Comment by alexplumb** [comment]
Can you do a build size comparison between jpg and png images?

**Comment by masbaehr** [comment]
Not really much smaller, actually it is even bigger and lower quality. 
I'm now testing with https://rotemdan.github.io/lzutf8/demo/ if it can be compressed further, but it would also mean harder maintenance

**Comment by davityavryan** [comment]
Maybe just go with [flag sprite that google uses](http://ssl.gstatic.com/i18n/flags/48x32/nobevel/40b411e8384b10c60bd78340cafbda86/flags.png) 33kb GZip-ed (just open https://myaccount.google.com/phone to see the flag)

**Comment by masbaehr** [comment]
That one is not complete as google does not support phone numbers for every country in the world while as this lib should be universal. Also it still would make it hard to maintain, if for instance one country changes flag (which may seem like a rare thing, but still it happens: https://en.wikipedia.org/wiki/List_of_sovereign_states_by_date_of_current_flag_adoption )

**Comment by davityavryan** [comment]
ok, I agree.

Different question though. Maybe make sense to go with SVG version? In that case quality is guaranteed and file size might be even smaller. Also eliminates need for Less file for sprite.

**Comment by masbaehr** [comment]
The problem with SVG is there are some flags which are very big as SVG because they are complex. For example Spain. This flag alone is bigger than most other flags combined. Therefore the best solution would be a build-script which generates a PNG sprite or Base64 images from SVG. In my pull request i've added the images. And the genereation was done with an external tool i've posted here: https://github.com/masbaehr/flag-icon-css-transcoder

**Comment by bherila** [comment]
Perhaps we would just do better if we took a dependency on https://www.npmjs.com/package/country-flag-icons which seems to have done all this hard work for us (and also provides more options which we could expose)?

**Comment by alexplumb** [comment]
Support for `country-flag-icons` has been added in the latest update

**Pull request closed without merging**
