### PR TITLE
Convert Less styles to JSS to remove style-loader dependency and fix SSR build issues

### PR DESCRIPTION
**Pull request by braxex**
**Background**

There are a few open issues  (#15, #24, #49) that deal with SSR rendering and `window is not defined` errors. I've commented on issue #24 with more details on the error and have linked a [minimal reproduction](https://github.com/braxtonex/minimal-reproduction) of it. 

This PR is a potential solution to these issues.

**Proposed Solution**

Because `material-ui-phone-number` already has a CSS in JS styling solution using `withStyles()` we could convert all Less styling to JSS and remove `less` & `style-loader`, along with other associated loaders (`css-loader` & `less-loader`). 

Changes:
- Converts the flag styles from Less to JSS
- Removes the now unneeded dependencies and associated webpack rules
- Adds classes necessary to pass JSS styling to components

It appears to work well and would not be a breaking change. 

I'd love to hear any feedback you have @alexplumb !

### CODE REVIEW

**Comment by vishalvijay** [comment]
I tested this PR in my project. Works as expected. Even #24 issue got fixed with this.

**Comment by braxex** [comment]
@vishalvijay 


> I tested this PR in my project. Works as expected. Even #24 issue got fixed with this.

Glad to hear it was helpful. I ended up turning this fix into a stand-alone package for use until the PR gets merged - feel free to use. https://www.npmjs.com/package/mui-phone-input-ssr

**Comment by llampwall** [comment]
@braxex thanks for that. works great except when i try to register it with react-hook-form. i think #56 is my issue. is there any chance you can merge in the small changes made there?

**Comment by llampwall** [comment]
actually scratch that, i got it to work with some workarounds.

**Comment by braxex** [comment]
Closing this PR as it's been over a year. I ended up turning the original fix into a stand-alone package for MUI phone input with SSR support.

NPM: https://www.npmjs.com/package/mui-phone-input-ssr
GitHub: https://github.com/braxex/mui-phone-input-ssr

**Comment by bherila** [comment]
I can merge it, am trying to revive support for this package.

**Comment by braxex** [comment]
@bherila That would be great!

**Pull request closed without merging**
