### PR TITLE
Upgrade Material-ui v5.0.0  new brand name package @mui/*

### PR DESCRIPTION
**Pull request by karthik1704**
- [x] ~~Upgrade material-ui v5 rc1~~
- [x] Upgrade mui v5 rc1 to mui v5.0.0
- [x]  @material-ui/core -> @mui/material 
- [x]  @material-ui/styles -> @mui/styles 
- [x] update old material import with new branded name imports

### CODE REVIEW

**Comment by Phrensoua** [comment]
Hello guys,

Any chance to see this in soon?

Cheers!

**Comment by jeanlucmongrain** [comment]
2 weeks later, no update? this project is dead?

**Comment by karthik1704** [comment]
This project not dead , I think so.
- Recent commit one month are less
-  maintainer busy or working  , That's why this repo not updating regularly but updating sometime soon , 
- so give sometime

**Comment by alexplumb** [comment]
I've published a v3 of this package which includes support for mui v5

**Pull request closed without merging**
